import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import ElementPlus from 'element-plus';
import 'element-plus/lib/theme-chalk/index.css';
import '@/assets/css/common.less';
import locale from 'element-plus/lib/locale/lang/zh-cn';
import { dialogDrag } from '@/utils/directives';
// import hljs from 'highlight.js';
// import 'highlight.js/styles/monokai-sublime.css';

const app = createApp(App);
app.config.performance = true;
// app.directive('highlight', highlightjs);
// app.use(hljs.vuePlugin);
app.directive('dialogDrag', dialogDrag);
app.use(ElementPlus, { size: 'small', locale });
app.use(store);
app.use(router);
app.mount('#app');
